### ISSUE TITLE
Workspace selecter should validate that at least one is selected

### ISSUE THREAD

**Issue by cdupuis** [atomist/cli#62]

**Comment by jessitron** [comment]
huh, when I hit enter with just one workspace in the menu, did that not select it?

... because I just ran through this flow, having one workspace already created because I did "Get Started For Free" in the web, and it resulted in an empty workspaceIds: [] in my config, which resulted in an exception in `atomist start`

**Comment by jessitron** [comment]
This is important because it exhibits as an exception on `atomist start`
This is not a feature request,  this is a bug.
